### ISSUE TITLE
Error installing bundler every hour for four days

### ISSUE THREAD

**Issue by kkew3** [jeffreytse/jekyll-deploy-action#71]
From December 16 I have been receiving "Build and deploy to github pages: all jobs have failed" email every hour. I thought it would go away on its own, but it did not. I didn't make any commits these days and the issue occurred all of a sudden. The log (e.g. this link: https://github.com/kkew3/kkew3.github.io/actions/runs/7258117479/job/19772949278) goes like this:

```
/usr/bin/docker run --name b0e4d47954ecea61a2421782d75b664f8bc1ff_97724a --label b0e4d4 --workdir /github/workspace --rm -e "INPUT_PROVIDER" -e "INPUT_TOKEN" -e "INPUT_REPOSITORY" -e "INPUT_BRANCH" -e "INPUT_JEKYLL_SRC" -e "INPUT_JEKYLL_CFG" -e "INPUT_JEKYLL_BASEURL" -e "INPUT_BUNDLER_VER" -e "INPUT_CNAME" -e "INPUT_ACTOR" -e "INPUT_PRE_BUILD_COMMANDS" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/kkew3.github.io/kkew3.github.io":"/github/workspace" b0e4d4:7954ecea61a2421782d75b664f8bc1ff
Starting the Jekyll Deploy Action
Initialize environment
:: Synchronizing package databases...
 core downloading...
 extra downloading...
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Package (36)                  Old Version  New Version  Net Change  Download Size

core/archlinux-keyring        20231107-1   20231207-1     0.02 MiB       1.15 MiB
core/bash                     5.2.015-5    5.2.021-1      0.00 MiB       1.81 MiB
core/ca-certificates-mozilla  3.94-1       3.95-1        -0.03 MiB       0.36 MiB
core/curl                     8.4.0-2      8.5.0-1        0.03 MiB       1.21 MiB
core/gettext                  0.22.3-1     0.22.4-1       0.00 MiB       1.84 MiB
core/glib2                    2.78.1-1     2.78.3-1       0.00 MiB       3.82 MiB
core/gnupg                    2.2.41-2     2.4.3-2        0.87 MiB       2.65 MiB
core/gnutls                   3.8.1-2      3.8.2-1        0.02 MiB       2.76 MiB
core/gpgme                    1.23.1-1     1.23.2-1       0.00 MiB       0.47 MiB
core/hwdata                   0.376-1      0.377-1        0.04 MiB       1.57 MiB
core/iana-etc                 20231018-1   20231117-1     0.00 MiB       0.39 MiB
core/icu                      73.2-2       74.2-1        -1.10 MiB      11.13 MiB
core/iptables                 1:1.8.9-1    1:1.8.10-1     0.00 MiB       0.43 MiB
core/kbd                      2.6.3-1      2.6.4-1        0.00 MiB       1.25 MiB
core/libbpf                   1.2.2-1      1.3.0-1        0.03 MiB       0.24 MiB
core/libcap                   2.69-1       2.69-3        -0.06 MiB       0.68 MiB
core/libgcrypt                1.10.2-1     1.10.3-1       0.00 MiB       0.58 MiB
core/libksba                  1.6.4-1      1.6.5-1        0.00 MiB       0.14 MiB
core/libnl                    3.8.0-1      3.9.0-1        0.00 MiB       0.41 MiB
core/libp11-kit               0.25.2-1     0.25.3-1       0.00 MiB       0.50 MiB
core/libsecret                0.21.1-1     0.21.2-1       0.00 MiB       0.19 MiB
core/libxml2                  2.11.5-1     2.12.3-1       0.01 MiB       0.82 MiB
core/licenses                 20231011-1   20231215-1     0.00 MiB       0.11 MiB
core/openssl                  3.1.4-1      3.2.0-1        0.72 MiB       4.90 MiB
core/p11-kit                  0.25.2-1     0.25.3-1       0.00 MiB       0.23 MiB
core/perl                     5.38.0-1     5.38.1-1      -0.03 MiB      20.23 MiB
core/pkgconf                  1.8.1-1      2.1.0-2        0.01 MiB       0.06 MiB
core/readline                 8.2.001-2    8.2.007-1      0.00 MiB       0.32 MiB
core/sqlite                   3.44.0-1     3.44.2-2       0.07 MiB       1.63 MiB
installing ruby-etc...
installing ruby-fcntl...
installing ruby-fiddle...
installing ruby-fileutils...
installing ruby-find...
installing ruby-forwardable...
installing ruby-getoptlong...
installing ruby-io-console...
installing ruby-io-nonblock...
installing ruby-io-wait...
installing ruby-ipaddr...
installing ruby-reline...
installing ruby-irb...
installing ruby-json...
installing ruby-logger...
installing ruby-mutex_m...
installing ruby-uri...
installing ruby-net-http...
installing ruby-stringio...
installing ruby-time...
installing ruby-open-uri...
installing ruby-psych...
installing ruby-racc...
installing ruby-rdoc...
installing ruby-tmpdir...
installing ruby-stdlib...
installing ruby-minitest...
installing ruby-power_assert...
installing ruby-rake...
installing ruby-rexml...
installing ruby-test-unit...
installing ruby-bundledgems...
installing ruby...
Optional dependencies for ruby
    ruby-docs: Ruby documentation
    tk: for Ruby/TK
installing ruby-bundler...
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
ruby 2.7.8p225 (2023-03-30 revision 1f4d455848) [x86_64-linux]
Bundler version 2.1.4 (2023-12-19 commit unknown)
Restore modification time of all git files
Initial comptible bundler
WARNING:  You don't have /github/home/.gem/ruby/2.7.0/bin in your PATH,
	  gem executables will not run.
ERROR:  Error installing bundler:
	The last version of bundler (>= 0) to support your Ruby & RubyGems was 2.4.22. Try installing it with `gem install bundler -v 2.4.22`
	bundler requires Ruby version >= 3.0.0. The current ruby version is 2.7.8.225.
Starting bundle install
/usr/lib/ruby/2.7.0/rubygems.rb:277:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
	from /usr/lib/ruby/2.7.0/rubygems.rb:296:in `activate_bin_path'
	from /usr/sbin/bundle:25:in `<main>'
```

I can build the pages locally using `bundle exec jekyll serve` without any problem.

I have no idea what's going on and how I should do to fix it. Thanks in advance for help!

**Comment by jeffreytse** [comment]
Hi @kkew3 

This issue has been fixed in #70 , please use the latest version which is master branch in your github action as below:

```yml
- uses: jeffreytse/jekyll-deploy-action@master
   with:
      provider: 'github'
      token: ${{ secrets.GITHUB_TOKEN }} # It's your Personal Access Token(PAT)
```

Thanks & Regards

**Comment by kkew3** [comment]
Thank you so much for your help! Where should I make the change locally? Or somewhere else?

**Comment by jeffreytse** [comment]
@kkew3 You can also use `jeffreytse/jekyll-deploy-action@v0.5.1`, just simply modify your github action config in your repository.

**Comment by kkew3** [comment]
Sorry but I didn't quite understand. Should I specify the bundler version as `'~>2.4.0'`, `''` or leave it as the default `'>=0'`? Thank you so much!

**Comment by jeffreytse** [comment]
@kkew3 Both `'~>2.4.0'` and `''` work, as `>=0` will let it install the latest bundler version, as the latest bundler version requires `Ruby >=3.0.0`, that's why you met this bundler issue. : )

**Comment by kkew3** [comment]
Problem solved. Thanks again!

**Comment by jeffreytse** [comment]
> Problem solved. Thanks again!

You're welcome, welcome to star this project for further updates in the future. : )
