### ISSUE TITLE
Can't install the correct Bundler version

### ISSUE THREAD

**Issue by floriankraemer** [jeffreytse/jekyll-deploy-action#77]
I'm new to Jekyll and this GH Action, maybe I did something wrong, but if I got the docs right, then I should be able to define the right version in the workflow file and the action should use that version, no? 

So I defined `bundler_ver: '2.5.5'` this but I still get this:

```
| Traceback (most recent call last):
|       2: from /usr/sbin/bundle:25:in `<main>'
|       1: from /usr/lib/ruby/2.7.0/rubygems.rb:296:in `activate_bin_path'
| /usr/lib/ruby/2.7.0/rubygems.rb:277:in `find_spec_for_exe': Could not find 'bundler' (2.5.5) required by your /home/florian/projects/jekyll/Gemfile.lock. (Gem::GemNotFoundException)
| To update to the latest version installed on your system, run `bundle update --bundler`.
| To install the missing version, run `gem install bundler:2.5.5`
```

Am I doing something wrong or is that a bug?

**Comment by jeffreytse** [comment]
Hi @floriankraemer 

Thanks for your question, the issue why you can't install `bundler:2.5.5` is that required `ruby>=3.0.0`, you can check from [here](https://rubygems.org/gems/bundler/versions/2.5.5).

Thanks & Regards

**Comment by jeffreytse** [comment]
Hi @floriankraemer 

I think this issue should be settled down with the latest version of [v0.6.0](https://github.com/jeffreytse/jekyll-deploy-action/releases/tag/v0.6.0), you can specify the compatible ruby version and bundler version for your project.

Thanks & Regards
