### ISSUE TITLE
undefined method untaint in _layouts post.html

### ISSUE THREAD

**Issue by kkew3** [jeffreytse/jekyll-deploy-action#89]
Hi. Last time in #71 I set `jeffreytse/jekyll-deploy-action` to `v0.5.1`. A couple of days ago it started to raise [error](https://github.com/kkew3/kkew3.github.io/actions/runs/10876751885/job/30177462222):

> error: RPC failed; HTTP 400 curl 92 HTTP/2 stream 7 was not closed cleanly: CANCEL (err 8)

I try to resolve it by changing to `jeffreytse/jekyll-deploy-action@master`. But then it raises another [error](https://github.com/kkew3/kkew3.github.io/actions/runs/10876868393/job/30177403708):

```
Liquid Exception: undefined method `untaint' for "用TCL（工具命令语言）管理Tornado (for VxWorks) 可启动工程":String in /_layouts/post.html
jekyll 3.9.2 | Error:  undefined method `untaint' for "用TCL（工具命令语言）管理Tornado (for VxWorks) 可启动工程":String
/github/workspace/vendor/bundle/ruby/3.2.0/gems/liquid-4.0.3/lib/liquid/standardfilters.rb:42:in `escape': undefined method `untaint' for "用TCL（工具命令语言）管理Tornado (for VxWorks) 可启动工程":String (NoMethodError)

      CGI.escapeHTML(input.to_s).untaint unless input.nil?
                                ^^^^^^^^
	from /github/workspace/vendor/bundle/ruby/3.2.0/gems/liquid-4.0.3/lib/liquid/strainer.rb:56:in `invoke'
	from /github/workspace/vendor/bundle/ruby/3.2.0/gems/liquid-4.0.3/lib/liquid/context.rb:86:in `invoke'
	from /github/workspace/vendor/bundle/ruby/3.2.0/gems/liquid-4.0.3/lib/liquid/variable.rb:84:in `block in render'
	from /github/workspace/vendor/bundle/ruby/3.2.0/gems/liquid-4.0.3/lib/liquid/variable.rb:82:in `each'
	from /github/workspace/vendor/bundle/ruby/3.2.0/gems/liquid-4.0.3/lib/liquid/variable.rb:82:in `inject'
	from /github/workspace/vendor/bundle/ruby/3.2.0/gems/liquid-4.0.3/lib/liquid/variable.rb:82:in `render'
	from /github/workspace/vendor/bundle/ruby/3.2.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
	from /github/workspace/vendor/bundle/ruby/3.2.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:80:in `render'
	from /github/workspace/vendor/bundle/ruby/3.2.0/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
	from /github/workspace/vendor/bundle/ruby/3.2.0/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
	from /github/workspace/vendor/bundle/ruby/3.2.0/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
	from /github/workspace/vendor/bundle/ruby/3.2.0/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
	from /github/workspace/vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.2/lib/jekyll/liquid_renderer/file.rb:30:in `block (2 levels) in render!'
	from /github/workspace/vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.2/lib/jekyll/liquid_renderer/file.rb:42:in `measure_bytes'
	from /github/workspace/vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.2/lib/jekyll/liquid_renderer/file.rb:29:in `block in render!'
	from /github/workspace/vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.2/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
	from /github/workspace/vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.2/lib/jekyll/liquid_renderer/file.rb:28:in `render!'
	from /github/workspace/vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:126:in `render_liquid'
	from /github/workspace/vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:195:in `render_layout'
	from /github/workspace/vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:158:in `place_in_layouts'
	from /github/workspace/vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:88:in `render_document'
	from /github/workspace/vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:62:in `run'
	from /github/workspace/vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.2/lib/jekyll/site.rb:479:in `render_regenerated'
	from /github/workspace/vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.2/lib/jekyll/site.rb:464:in `block (2 levels) in render_docs'
	from /github/workspace/vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.2/lib/jekyll/site.rb:463:in `each'
	from /github/workspace/vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.2/lib/jekyll/site.rb:463:in `block in render_docs'
	from /github/workspace/vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.2/lib/jekyll/site.rb:462:in `each_value'
	from /github/workspace/vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.2/lib/jekyll/site.rb:462:in `render_docs'
	from /github/workspace/vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.2/lib/jekyll/site.rb:191:in `render'
	from /github/workspace/vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.2/lib/jekyll/site.rb:71:in `process'
	from /github/workspace/vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.2/lib/jekyll/command.rb:28:in `process_site'
	from /github/workspace/vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:65:in `build'
	from /github/workspace/vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:36:in `process'
	from /github/workspace/vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /github/workspace/vendor/bundle/ruby/3.2.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /github/workspace/vendor/bundle/ruby/3.2.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /github/workspace/vendor/bundle/ruby/3.2.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /github/workspace/vendor/bundle/ruby/3.2.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /github/workspace/vendor/bundle/ruby/3.2.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /github/workspace/vendor/bundle/ruby/3.2.0/gems/jekyll-3.9.2/exe/jekyll:15:in `<top (required)>'
	from /github/workspace/vendor/bundle/ruby/3.2.0/bin/jekyll:25:in `load'
	from /github/workspace/vendor/bundle/ruby/3.2.0/bin/jekyll:25:in `<top (required)>'
	from /github/workspace/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.22/lib/bundler/cli/exec.rb:58:in `load'
	from /github/workspace/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.22/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /github/workspace/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.22/lib/bundler/cli/exec.rb:23:in `run'
	from /github/workspace/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.22/lib/bundler/cli.rb:492:in `exec'
	from /github/workspace/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.22/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
	from /github/workspace/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.22/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /github/workspace/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.22/lib/bundler/vendor/thor/lib/thor.rb:[527](https://github.com/kkew3/kkew3.github.io/actions/runs/10876868393/job/30177403708#step:5:528):in `dispatch'
	from /github/workspace/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.22/lib/bundler/cli.rb:34:in `dispatch'
	from /github/workspace/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.22/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
	from /github/workspace/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.22/lib/bundler/cli.rb:28:in `start'
	from /github/workspace/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.22/exe/bundle:37:in `block in <top (required)>'
	from /github/workspace/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.22/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /github/workspace/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.22/exe/bundle:29:in `<top (required)>'
	from /github/home/.asdf/installs/ruby/3.2.0/bin/bundle:25:in `load'
	from /github/home/.asdf/installs/ruby/3.2.0/bin/bundle:25:in `<main>'
```

Interestingly, I can't grep out anything in https://github.com/kkew3/kkew3.github.io that matches "untaint".

Thank you so much for your help!

**Comment by kkew3** [comment]
After many trail and errors, I eventually get rid of the `untaint` issue. But the RPC issue

> error: RPC failed; HTTP 400 curl 92 HTTP/2 stream 7 was not closed cleanly: CANCEL (err 8)

remains. Any help is appreciated!

**Comment by kkew3** [comment]
I solve the RPC issue by:

```yaml
- uses: jeffreytse/jekyll-deploy-action@v0.6.0
  with:
    pre_build_commands: |
      git config --global http.version HTTP/1.1
      git config --global http.postBuffer 157286400
```

according to https://github.com/orgs/community/discussions/55820#discussioncomment-5947439.

**Comment by pfaffman** [comment]
Thanks, @kkew3!!! That's a huge help. I can update my site again.

**Comment by kkew3** [comment]
For future reference, the `untaint` issue above:

https://github.com/jeffreytse/jekyll-deploy-action/issues/89#issue-2527421670

origins from a jekyll bug https://github.com/jekyll/jekyll/issues/9233.
